config/routes.rb
CakeFundraising::Application.routes.draw do

  devise_for :sponsors
  devise_for :fundraisers
  get "stats/index"
  root :to => "home#index"

  match "confirmation", to: "confirmation#index", via: [:get]
  match "stats", to: "stats#index", via: [:get]

  namespace :fundraisers do
    resources :campaigns
  end

  resources :pledges

  namespace :sponsor do
    resources :pledges

    resources :campaigns do
      resources :pledges
    end
  end
end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  belongs_to :category

  has_many :pledges
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :campaigns
end

app/models/donate_kind.rb
class DonateKind < ActiveRecord::Base
end

app/models/fundraiser.rb
class Fundraiser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable
end

app/models/pledge.rb
class Pledge < ActiveRecord::Base
  belongs_to :donate_kind
  belongs_to :campaign
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/confirmation_controller.rb
class ConfirmationController < ApplicationController
  impressionist

  def index
  end
end

app/controllers/fundraisers/application_controller.rb
class Fundraisers::ApplicationController < InheritedResources::Base
end

app/controllers/fundraisers/campaigns_controller.rb
class Fundraisers::CampaignsController < Fundraisers::ApplicationController

  def permitted_params
    params.permit(campaign: [:headline, :story, :logo, :category])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  impressionist

  def index
  end
end

app/controllers/pledges_controller.rb
class PledgesController < InheritedResources::Base
end

app/controllers/sponsor/application_controller.rb
class Sponsor::ApplicationController < InheritedResources::Base
end

app/controllers/sponsor/pledges_controller.rb
class Sponsor::PledgesController < InheritedResources::Base
  belongs_to :campaign

  def permitted_params
    params.permit(pledge: [:headline, :donate, :donate_kind_id, :not_to_exceed, :redirect_click, :per_uniq_clicl_on])
  end

end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
  respond_to :html, :json

  def index
    @impressions = Impression.all
    @impressions_total = @impressions.count
    @impressions_by_session = Impression.group(:session_hash).all.count
    @impressions_on_confirmation = Impression.where(controller_name: "confirmation").group(:session_hash).all.count
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/confirmation_helper.rb
module ConfirmationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sponsor/pledges_helper.rb
module Sponsor::PledgesHelper
end

app/views/application/_messages.html.slim
/ Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    div class="alert alert-#{name == :notice ? "success" : "danger"}"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"] ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/application/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
      = link_to 'Stats', stats_path, class: 'navbar-brand'
      = link_to 'Create Campaign', new_fundraisers_campaign_path, class: 'navbar-brand'

app/views/application/_share_this.html.slim
p
  span.st_sharethis_large displayText="ShareThis"
  span.st_facebook_large displayText="Facebook"
  span.st_twitter_large displayText="Tweet"
  span.st_linkedin_large displayText="LinkedIn"
  span.st_pinterest_large displayText="Pinterest"
  span.st_email_large displayText="Email"

app/views/confirmation/index.html.slim
#redirect_on_load.panel.panel-default
  .panel-body
    p Thank you for your participation! We appreciate you supporting the cause.
    p In approximately 3 seconds, you will now be redirected to a page of our sponsor.

app/views/fundraisers/campaigns/new.html.slim
h2 Create Your Campaign
= simple_form_for [:fundraisers, @campaign], defaults: { input_html: { class: 'form-control' } } do |f|
  ul#myTab.nav.nav-tabs
    li.active
      a href="#story" data-toggle="tab" Tell Your Story
    li
      a href="#your_look" data-toggle="tab" Design Your Look
    li
      a href="#sponsor_levels" data-toggle="tab" Set Sponsors Levels
    li
      a href="#donations" data-toggle="tab" Accept Donations
    li
      a href="#previen_and_edit" data-toggle="tab" Preview & Edit
    li
      a href="#solicit_sponsors" data-toggle="tab" Solicit Sponsors

  .tab-content
    .tab-pane.active#story
      .col-md-7
        .form-group
          = f.input :headline, placeholder: 'Mission Statement - 40 characters', label: 'Campaign Headline'
          p.help-block Campaign Launch and End Date (you can change later)
          .well style="height:75px;"
            .col-md-5
              .form-group
                #datetimepicker_start.datetimepicker.input-group.date
                  input.form-control type="text"
                  span.input-group-addon
                    span.glyphicon.glyphicon-calendar
            .col-md-5
              .form-group
                #datetimepicker_end.datetimepicker.input-group.date
                  input.form-control type="text"
                  span.input-group-addon
                    span.glyphicon.glyphicon-calendar
          = f.input :story, label: 'Tell Your Story', :input_html => { :rows => 10 }
      .col-md-5
        .col-md-7
          = image_tag asset_path('ruby.png')
          a.btn.btn-info.center-block Upload Your Logo
        .col-md-5
          .well.small.text-info
            | FR must be able to crop and reposition the image within a fixed frame as desired. 
            | Must be able to delete and replace the image. When the image uploads and appears here, it should also appear under the preview tab
        = f.association :category, label: 'Choose fundraising category for this campaign'
    .tab-pane#your_look
    .tab-pane#sponsor_levels
    .tab-pane#donations
    .tab-pane#previen_and_edit
    .tab-pane#solicit_sponsors
  .action_buttons.pull-right
    = f.button :submit, class: 'btn-primary'

app/views/fundraisers/campaigns/show.html.slim
h1 = "Campaign #{@campaign.headline}"

p this is the link you to give to your sponsors
p.well = link_to new_sponsor_campaign_pledge_url(@campaign), new_sponsor_campaign_pledge_path(@campaign)

app/views/home/index.html.slim
.background
  h3 Help great organizations 
  h3 drive traffic to your
  h3 website!

  br
  br
  p = link_to 'Get Started', new_sponsor_registration_path, class: 'btn btn-info btn-lg'

  h2.text-right Find and Support Great Causes!

app/views/layouts/_navigation.html.slim
/ navigation styled for Bootstrap 3.0
nav.navbar.navbar-inverse.navbar-fixed-top
  .container
    .navbar-header
      button.navbar-toggle[type="button" data-toggle="collapse" data-target=".navbar-collapse"]
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
      = link_to 'Stats', stats_path, class: 'navbar-brand'
      = link_to 'Create Campaign', new_fundraisers_campaign_path, class: 'navbar-brand'
      = link_to 'Create Pledge', new_sponsor_pledge_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      ul.nav.navbar-nav
        == render 'layouts/navigation_links'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta[name="viewport" content="width=device-width, initial-scale=1.0"]
    title
      = content_for?(:title) ? yield(:title) : 'Cake Fundraising'
    meta name="description" content="#{content_for?(:description) ? yield(:description) : 'Cake Fundraising'}"
    == stylesheet_link_tag "application", :media => "all"
    == javascript_include_tag "application"

    == csrf_meta_tags
  body
    header
      == render 'navigation'
    main[role="main"]
      .container
        == render 'messages'
        == yield

app/views/pledges/show.html.slim
p = "Campaign: #{ @pledge.campaign.headline }"
p = "Sponsor: #{ @pledge.headline }"
p = link_to 'Click to Help – Its Free', confirmation_path, class: 'btn btn-primary btn-lg'

== render 'share_this'

app/views/sponsor/pledges/new.html.slim
h2 Create Your Pledge
= simple_form_for [:sponsor, @campaign, @pledge], defaults: { input_html: { class: 'form-control' } } do |f|
  ul#myTab.nav.nav-tabs
    li.active
      a href="#pledge" data-toggle="tab" Pledge
    li
      a href="#story" data-toggle="tab" Tell Your Story
    li
      a href="#your_look" data-toggle="tab" Design Your Look
    li
      a href="#donations" data-toggle="tab" Add a Coupon
    li
      a href="#previen_and_edit" data-toggle="tab" Add a Sweepstake
    li
      a href="#solicit_sponsors" data-toggle="tab" Pledge Preview
    li
      a href="#solicit_sponsors" data-toggle="tab" Launch Your Pledge

  .tab-content
    .tab-pane#story
      .col-md-7
        .form-group
          = f.input :headline, placeholder: 'Mission Statement - 40 characters', label: 'Campaign Headline'
          p.help-block Campaign Launch and End Date (you can change later)
          .well style="height:75px;"
            .col-md-5
              .form-group
                #datetimepicker_start.datetimepicker.input-group.date
                  input.form-control type="text"
                  span.input-group-addon
                    span.glyphicon.glyphicon-calendar
            .col-md-5
              .form-group
                #datetimepicker_end.datetimepicker.input-group.date
                  input.form-control type="text"
                  span.input-group-addon
                    span.glyphicon.glyphicon-calendar
          = f.input :story, label: 'Tell Your Story', :input_html => { :rows => 10 }
      .col-md-5
        .col-md-7
          = image_tag asset_path('ruby.png')
          a.btn.btn-info.center-block Upload Your Logo
        .col-md-5
          .well.small.text-info
            | FR must be able to crop and reposition the image within a fixed frame as desired. 
            | Must be able to delete and replace the image. When the image uploads and appears here, it should also appear under the preview tab
    .tab-pane#your_look
    .tab-pane#pledge.active
      .col-md-6
        = f.input :donate, label: 'I agree to donate'
      .col-md-6
        = f.association :donate_kind, label: 'In'
      = f.input :per_uniq_clicl_on, label: 'per unique click to'
      = f.input :not_to_exceed, label: 'up to an amount not to exceed $'
      = f.input :redirect_click, label: 'Please Direct Clicks to:'

    .tab-pane#donations
    .tab-pane#previen_and_edit
    .tab-pane#solicit_sponsors
  .action_buttons.pull-right
    = f.button :submit, class: 'btn-primary'

app/views/sponsor/pledges/show.html.slim
h1 Pledge created!

p This is the url

p.well
  = link_to pledge_url(@pledge), pledge_path(@pledge)

app/views/stats/index.html.slim
h1 Stats

table#stats.table.table-striped
  thead
    tr
      th # of Impressions
      th # of Unique Clicks
      th # on Confirmation
  tbody
    tr
      td#total = @impressions_total
      td#by_session = @impressions_by_session
      td#confirmation = @impressions_on_confirmation

app/views/stats/index.json.erb
{"stats":
  { "total": <%= @impressions_total %>,
    "by_session": <%= @impressions_by_session %>,
    "confirmation": <%= @impressions_on_confirmation %>
  }
}